### ISSUE TITLE
Issue making alps: no such file <boost/log/utility/empty_deleter.hpp>

### ISSUE THREAD

**Issue by ypluo** [snalli/mnemosyne-gcc#21]
I tried making ALPS following the intruction in README but  it occured to an error saying that  file <boost/log/utility/empty_deleter.hpp> is not found, the message is like this:

```
/home/lyp/mnemosyne-gcc-alps/usermode/library/pmalloc/include/alps/src/common/log.cc:29:10: fatal error: boost/log/utility/empty_deleter.hpp: No such file or directory
 #include <boost/log/utility/empty_deleter.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

I search the file , it's include only in /usr/include/boost/utility, which seems not the right file.  I download a file  [empty_deleter.hpp](https://gerrit.cesnet.cz/plugins/gitiles/github/boostorg/log/+/a7c4e0e319481878a96a690b2d8eec244594f99a/include/boost/log/utility/empty_deleter.hpp) and it worked. 

By the way, I work on ubuntu 18.04.

**Comment by snalli** [comment]
cool, if u have a fix, can u pls submit a patch ?

**Comment by swapnilh** [comment]
That's not the right fix. I've forgotten to push in a fix for this issue.
I'll send it in tonight.

**Comment by swapnilh** [comment]
Hey Ypluo,

Please check out the fix here: https://github.com/snalli/mnemosyne-gcc/pull/22

**Comment by ypluo** [comment]
ok, I see, it looks much better, thanks!

**Comment by ypluo** [comment]
> Hey Ypluo,
> 
> Please check out the fix here: #22
ok, I see, it looks much better, thanks!
